diff --git a/Makefile b/Makefile
index c1eed73..5246779 100644
--- a/Makefile
+++ b/Makefile
@@ -82,7 +84,7 @@ helper:			helper.o
 helper.o authbind.o:	authbind.h
 
 $(LIBTARGET):		libauthbind.o
-		ld -shared -soname $(LIBCANON) -o $@ $< $(LIBS)
+		$(LD) -shared -soname $(LIBCANON) -o $@ $< $(LIBS)
 
 clean distclean:
 		rm -f $(TARGETS) *.o *~ ./#*# *.bak *.new core
